version: "3"

services:
  web:
    build: .
    command: >
      bash -c "
      python manage.py migrate
      && python manage.py runserver 0:8000
      "    
    ports:
      - "8000:8000"
    volumes:
      - .:/web
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres